name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # update the version to the latest
      with:
        ref: main # specify the branch to checkout
    - name: Setup Java
      uses: actions/setup-java@v1 # update the version to the latest
      with:
        java-version: '20' # update the Java version to 20
    - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
    - name: Build with Maven
      run: mvn clean install
      env:
        JDK_HOME: ${{ env.JAVA_HOME }} # set the JDK_HOME environment variable to JAVA_HOME